spec_version_minecraft = 1.20.1
spec_version_forge = 47.1.0

mod_id = ldiediet
mod_name = L'DieDiet
mod_version = 1.5.0
mod_group_id = com.levbu.ldiediet
mod_authors = User
description = Food boredom system that integrates with Diet mod. Eating the same food repeatedly reduces its effectiveness.

# Mappings
mapping_channel = parchment
mapping_version = 2023.09.03-1.20.1
